name: polymerize
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://dart-polymer.com
description: An Polymer 2.x support for Dart/DDC
version: 0.5.4
environment:
   sdk: ">=1.8.0 <2.0.0"

dependencies:
 dev_compiler:
  hosted:
   name: dev_compiler
   url: "http://pub.dart-polymer.com"
  version:  0.2.0-unofficial.2017022101
#  version:  0.2.0-unofficial.2017020101
#  version: 0.2.0-unofficial.2016111201
#  path: ../sdk/pkg/dev_compiler
#  git:
#   url: https://github.com/dart-lang/dev_compiler
 analyzer: any
 args: any
 stack_trace: any
 resource: any
 homedir: any
 logging_handlers: any
 glob: ^1.1.3
# pub_cache: any
# pub_client: any
 archive: any
 package_resolver: any
# dartson: '0.2.6'
# build:
#  git:
#   url: https://github.com/dart-lang/build.git
executables:
 polymerize: polymerize
dependency_overrides:
# analyzer: 0.29.1
# dev_compiler:
#  path: /home/vittorio/Develop/dart/sdk/pkg/dev_compiler
