name: polymerize
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://dart-polymer.com
description: An Polymer 2.x support for Dart/DDC
#publish_to: https://pub.dart-polymer.com
version: 0.9.6-dev
environment:
   sdk: ">=1.8.0 <2.0.0"

dependencies:
 build: ^0.10.0
 build_runner: ^0.4.0
 source_gen: ^0.7.0
 bazel_worker: "^0.1.4"
 code_builder: ^1.0.2
# dev_compiler:
#  hosted:
#   name: dev_compiler
#   url: "https://pub.dart-polymer.com"
#  version:  0.2.0-unofficial.2017042201
#  version:  0.2.0-unofficial.2017031301
#  version:  0.2.0-unofficial.2017020101
#  version: 0.2.0-unofficial.2016111201
#  path: ../sdk/pkg/dev_compiler
#  git:
#   url: https://github.com/dart-lang/dev_compiler
# analyzer: 0.30.0
 args: any
 code_transformers: any
 stack_trace: any
 resource: any
 homedir: any
 logging_handlers: any
# code_transformers: any
 glob: ^1.1.3
# pub_cache: any
# pub_client: any
 archive: any
 package_resolver: any
 barback: any
 test: any
 html5: ^0.1.7
# dartson: '0.2.6'
# build:
#  git:
#   url: https://github.com/dart-lang/build.git
executables:
 polymerize: polymerize
dependency_overrides:
# html5:
#   path: ../html_lib
# analyzer: 0.30.0
# analyzer: 0.29.1
# dev_compiler:
#  path: /home/vittorio/Develop/dart/sdk/pkg/dev_compiler
